- name: Locally build and tag phd-assess-meteor image
  tags:
    - pdf-build
    - never
  shell: |
    set -e -x
    npm run build && docker build --tag {{ phd_assess_pdf_image_tag }} ..
  delegate_to: localhost
  register: output_docker_build
- debug: var=output_docker_build.stdout_lines
  tags:
    - pdf-build
    - never

- name: Log into the Openshift docker repository and push the image
  tags:
    - pdf-push
    - never
  shell: |
    set -e -x
    oc whoami -t | docker login {{ openshift_image_registry }} -u unused --password-stdin
    docker push {{ phd_assess_pdf_image_tag }}
  register: output_push_image
  delegate_to: localhost
- debug: var=output_push_image.stdout_lines
  tags:
    - pdf-push
    - never

- name: phd-assess-pdf Deployment Config
  tags:
    - meteor
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: phd-assess-pdf
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: phd-assess-pdf
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: 1
            memory: 300M
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: phd-assess-pdf
        spec:
          containers:
            - env:
              - name: 'ZEEBE_ADDRESS'
                value: 'zeebe-broker:26500'
              - name: 'ZEEBE_TASK_TYPE'
                value: 'phdBuildPDF'
              - name: "{{ encryption_key_name }}"
                valueFrom:
                  secretKeyRef:
                    name: "{{ secret_name }}"
                    key: "{{ encryption_key_name }}"
              image: 'docker-registry.default.svc:5000/{{openshift_namespace}}/phd-assess-pdf:latest'
              imagePullPolicy: Always
              name: phd-assess-pdf
              resources:
                limits:
                  cpu: 1
                  memory: 300M
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - phd-assess-pdf
          from:
            kind: ImageStreamTag
            name: 'phd-assess-pdf:latest'
            namespace: "{{openshift_namespace}}"
