all:
  children:
    openshift_namespaces:
      # Members of this group are not really “hosts,” but rather, OpenShift namespaces.
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
        # The name of the namespace is the Ansible inventory name (as defined
        # in inventory/*.yml):
        openshift_namespace: "{{ inventory_hostname }}"
